version: "3.6"
services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    ports:
      - '5006:5006'
    volumes:
      - /volume1/docker/actual:/data:rw
    restart: on-failure:5

